# Profile section
profile:
  first_name: Felipe
  last_name: Sembay
  # picture: https://rodolfoferro.xyz/assets/images/profile.jpg   # Hosted picture
  picture: https://cdn.glitch.com/e97af72f-6650-41fb-b7ca-5a4cdd42ea0c%2F26767dca-bce5-4468-b208-5a526ffa20ed.image.png?v=1586440795169
  contact:
    address_one: Guarapuava-PR
    address_two:
    phone: 
  email: felipesembay91@gmail.com
  description: >
    Economista e Analista de Dados, apaixonado por Dados, padrões e tecnologia. 

# Social section
social:
  website: 
  github: https://github.com/felipesembay
  kaggle: https://www.kaggle.com/felipesembay
  linkedin: https://www.linkedin.com/in/felipe-sembay-80357364/
  facebook: https://www.facebook.com/felipe.sembay
  Dev :
  medium: https://medium.com/@felipesembay


# Experience section
experience:
  item0:
    position: Analista de dados
    company: 
    from: Abril 2018
    to: Maio 2018
    description: >
      Analise probabilistica em dados de call center, buscando prever quais dias dentro do mês os operadores conseguíriam mais acordos com os clientes.  
    link: 
    
  #reference: https://minerandodados.com.br/
  # item2:
  #   position: AI Consultant
  #   company: NULLSEC (Startup)
  #   from: July 2019
  #   to: September 2019
  #   description: >
  #     Working as an AI consultant for NULLSEC, a computer security company focused on ethical hacking. Particularly helping in the development of NullRansom, an analyzer-debugger software with the purpose of filtering TCP protocol requests, preventing preventively being targeted by malware and ransomware viruses.
  #   link: http://www.nullsec.site
  # item3:
  #   position: Lead ML Engineer
  #   company: Omdena
  #   from: May 2019
  #   to: July 2019
  #   description: >
  #     Lead ML engineer in Omdena's collaborative tree identification challenge to prevent fire outbursts. Contributed with the models developed and the data preprocessing (we develped a Python package for it).
  #   link: https://medium.com/omdena/building-ai-for-good-by-the-people-for-the-people-d98ad78b5001
  # item4:
  #   position: Jr. Python Software Developer
  #   company: CloudLinux
  #   from: February 2019
  #   to: May 2019
  #   description: >
  #     In charge of building automation solutions with Python. The tech stack used includes Scrapy, Luigi, requests, and MongoDB.
  # item5:
  #   position: AI Research Assistant
  #   company: Research Center in Mathematics (CIMAT A.C.)
  #   from: February 2018
  #   to: February 2019
  #   description: >
  #     On charge of doing research and building neural networks for computer vision problems, focused on applications and solutions for real industry issues. Deployed trained models to production.
  # reference: https://rodolfoferro.xyz/resume/


# Education section
education:
  item1:
    institution: Universidade Estadual do Centro Oeste -UNICENTRO
    program: Bacharelado em Ciências Econômicas
    description: Entre vários campos de estudo, a estatística/  econometria, e o uso de dados para prever comportamento e indicadores macroecnômicos.
    from: Fevereiro 2010
    to: Dezembro 2017
    
    
   


  item2:
    institution: Centro Universitário de Maringá - UNICESUMAR
    program: Bacharelado em Engenharia de Produção
    description: Matemática e áreas relacionados a gestão e conhecimento de negócios. 
    from: Outubro 2015
    to: Atualmente trancada - Previsão conclusão 2021
  # item3:
  #   institution: Harvard University
  #   program: Summer Internship – Adapting machine learning techniques for chemistry problems.
  #   description: Worked on a project to calibrate and predict molecular properties using Gaussian processes.
  #   from: June 2017
  #   to: August 2017
  # reference: https://rodolfoferro.xyz/resume/


# Community section:
community:
  item0:
    institution: Omdena
    program: Community Builder
    description: "Selected as a community builder at Omdena due to exemplary performance in their AI challenge on the tree identification challenge to prevent fire outbursts."
    from: September 2019
    to: Present
    link: https://omdena.com
  item1:
    institution: Future Lab
    program: Co-founder and Coordinator
    description: "Co-founder and coordinator of Future Lab, a community of tech developers for the future. We maily work under three axis: a) Develop awesome tech based projects, b) Share knowledge with the community, and c) Networking with other communities. As a member of Future Lab I have participated on big events such as Talent Land with an AI talk."
    from: April 2017
    to: Present
    link: https://futurelab.mx
  item2:
    institution: GitHub Education
    program: GitHub Campus Experts Program
    description: Mexican member of the GitHub Campus Experts Program, encouraging to empower other student communities. I also serve as a mentor in different events such as Startup Weekends, hackathons, innovation events, etc.
    from: October 2017
    to: Present
    link: https://githubcampus.expert/RodolfoFerro/
  item3:
    institution: Clubes de Ciencia México
    program: Guanajuato Comitee Member and Instructor
    description: Co-organizer of the intensive one-week summer science workshops of Clubes de Ciencia México in Guanajuato. Besides organizing, I have participated teaching science workshops (in particular a physics workshop, based on a Nobel Prize design, and artificial intelligence workshops) for high school and undergrad students.
    from: January 2015
    to: Present
    link: https://www.clubesdeciencia.mx
  item4:
    institution: Google Programs
    program: Google Student Ambassador and GDG
    description: Served as a Google Student Ambassador Latam for the University of Guanajuato, empowering the student community with Googleness and Google technologies to make their life easier. Currently helping the GDG León with tech talks and workshops about AI as a core member of the team. Do cool things that matter.
    from: August 2014
    to: July 2015
    link: https://www.meetup.com/es/GDGLeon/
  reference: https://rodolfoferro.xyz/resume/


# Skills section
tools:
  # Consider that the following are fa icons:
  #   https://fontawesome.com/icons?d=gallery&s=brands
  - github
  - trello
  - python
  - linux
  - r-project
  - linkedin
 
extra_skills:
  - Machine learning 
  - Data Analysis
  - Banco de Dados
  - Power BI
  - Tableau
  - Visualização de Dados
  


# Talks and workshops section
workshops:
  item0:
    event: TEDxUNAMLeón
    workshop: AI in modern times, February 2020.
    material:
    link: https://www.ted.com/tedx/events/35293
  item1:
    event: PyCon Colombia 2020
    workshop: 'Workshop – DLaaS: Building cloud-based intelligent solutions, February 2020.'
    material: https://github.com/RodolfoFerro/PyConCo20
    link: https://www.pycon.co/ponentes/rodolfo-ferro/
  item2:
    event: International Meeting on Artificial Intelligence and its Applications (RIIAA) 2.0.
    workshop: Workshop – Deep Learning as a Service (DLaaS), August 2019.
    material: https://github.com/RodolfoFerro/RIIAA19-DLaaS
    link: https://riiaa.org
  item3:
    event: LAB León Web Dev Crash Course 2019.
    workshop: Crash Course – Introduction to Web Development with Python and Flask, August 2019.
    material: https://github.com/RodolfoFerro/Flask101
    link: https://flask101.glitch.me
  item4:
    event: DevDay León 2019 by Hackademy.
    workshop: Workshop – (AI) API development with Python, August 2019.
    material: https://github.com/RodolfoFerro/PythonBaseAPI
    link:
  item5:
    event: Clubes de Ciencia México 2019.
    workshop: Workshop – Revealing the Hidden Hyperspectrum with Artificial Neurons, July 2019.
    material: https://rodolfoferro.xyz/hyperspectrum/
    link:
  item6:
    event: DevDay Mérida 2019.
    workshop: Workshop – Artificial Intelligence with Python, July 2019.
    material: https://github.com/RodolfoFerro/DevDayMid2019
    link:
  item7:
    event: Talent Land 2019.
    workshop: Talk – A.I. in modern times, April 2019.
    material:
    link: https://jaliscotalentland2019.sched.com/event/MzAs/inteligencia-artificial-en-tiempos-modernos
  item8:
    event: PythonDay México 2018.
    workshop: Talk – Data Science with Python, December 2018.
    material: https://github.com/RodolfoFerro/DataSciPy
    link:
  item9:
    event: PythonDay México 2018.
    workshop: Workshop – Machine Learning as a Service (MLaaS), November 2018.
    material: https://github.com/RodolfoFerro/MLaaS
    link:
  item10:
    event: HERE Hackathon at Technological University of Leon.
    workshop: Mentor on the event. Talk – Integration of Technological Solutions, November 2018.
    material: https://github.com/RodolfoFerro/HereHackathon
    link:
  item11:
    event: 6th. International Conference in Software Engineering Research and Innovation (CONISOFT).
    workshop: Workshop – Introduction to Neural Networks with Keras, October 2018.
    material: https://github.com/RodolfoFerro/CONISOFT2018
    link: http://conisoft.org/2018/public/
  reference: https://rodolfoferro.xyz/resume/


# Projects section
projects:
  item1:
    title: Analise dos dados de vôos ocorridos nos EUA no ano de 2015
    subtitle: Tableau
    description: Analisando correlações de vôos atrasados e cancelados em decorrência do clima
    link: https://public.tableau.com/profile/felipe.sembay#!/vizhome/ArquivosIII-ProjetoIVUdacity/Painel1
    github: https://public.tableau.com/profile/felipe.sembay#!/vizhome/ArquivosIII-ProjetoIVUdacity/Painel1
    img: https://img.freepik.com/vetores-gratis/decolagem-do-aviao-em-uma-pista-de-pouso-para-avioes-perto-do-terminal-sala-de-controle-na-torre_1441-2363.jpg?size=626&ext=jpg
    tags: [Visualização de Dados, Tableau]
    
    
  item2:
    title: Segmentação, classificação e Projeção de Receitas
    subtitle: Python, ARIMA, ETS, PROPHET, Cluster, Classificação
    description: Esse é o projeto final da Nanodegree em análise de dados, na qual foi replicado 100% no Python. Foi utilizado modelo para clusterização, classificação e série temporal. O principal objetivo desse projeto era segmentar todas as lojas por cluster, e prever a receita de produtos perecíveis. 
    link: https://www.linkedin.com/pulse/projeto-5-forecasting-parte-33-felipe-sembay/?trackingId=zeGmiDDzwtA3PmPeO66iyA%3D%3D
    github: https://github.com/felipesembay/Udacity/blob/master/Clusters/Projeto_Final.ipynb
    img: https://www.allstrategy.com.br/wp/wp-content/uploads/2016/07/projecao_de_vendas_3.jpg
    tags: [Pré Processamento de Dados, Modelo de Série Temporal, Arima, ETS, Prophet, Cluster, Modelo de classificação]
  
  item3:
    title: Modelo de Regressão Linear para previsão do preço de diamantes
    subtitle: Python, Pandas, Seaborn, Numpy
    description: Etapa 1 nesse projeto foi utilizado modelo de regressão linear para prever o preço de diamantes.
    link: https://github.com/felipesembay/Udacity/blob/master/Projeto1_Regressao_Linear/Diamonds.ipynb
    github: https://github.com/felipesembay/Udacity/blob/master/Projeto1_Regressao_Linear/Diamonds.ipynb
    img: https://cdn.glitch.com/e97af72f-6650-41fb-b7ca-5a4cdd42ea0c%2Fdiamonds.jpg
    tags: [Machine Learning, Regressão Linear, Python]
    
  item4:
    title: Prevendo a demanda de um novo catálogo.
    subtitle: Python, Pandas, Seaborn, Numpy, Regressão Linear
    description: Neste projeto foi utilizado Regressão Linear para prever qual seria o lucro de uma loja caso se fosse lançado um novo catálogo de produtos. 
    link: https://github.com/felipesembay/Udacity/blob/master/Projeto1%20-%20Catalogo/Projeto%20Catalogo%20Loja.ipynb
    github: https://github.com/felipesembay/Udacity/blob/master/Projeto1%20-%20Catalogo/Projeto%20Catalogo%20Loja.ipynb
    img: https://cdn.glitch.com/e97af72f-6650-41fb-b7ca-5a4cdd42ea0c%2Fcatalogo-virtual%20(1).webp?v=1588862114104
    tags: [Machine Learning, Regressão Linear, Python]
    
  item5:
    title: Classificação de Risco de Empréstimo de Crédito.
    subtitle: Python, Pandas, Seaborn, Numpy, Modelos de classificação
    description: Neste projeto foi utilizado modelos de classificação para prever quais pessoas teriam os seus pedidos de empréstimos aceitos e quais teriam o seu pedido negado.
    link: https://github.com/felipesembay/Udacity/blob/master/Projeto2_classificacao/Modelo_de_classificação_de_Crédito.ipynb
    github: https://github.com/felipesembay/Udacity/blob/master/Projeto2_classificacao/Modelo_de_classifica%C3%A7%C3%A3o_de_Cr%C3%A9dito.ipynb
    img: https://cdn.glitch.com/e97af72f-6650-41fb-b7ca-5a4cdd42ea0c%2F58d14e-Dinheiro.webp?v=1588875072529
    tags: [Machine Learning, Python, Classificação]
   
  item6:
    title: Projeção de Vendas de uma loja de Video Game.
    subtitle: Python, Pandas, Seaborn, Numpy, ETS, ARIMA, Prophet
    description: Neste projeto foi utilizado 3 modelos de série temporal diferente para prever a quantidade de video game vendidos ao longo de 15 meses. 
    link: https://github.com/felipesembay/Udacity/blob/master/Projeto4%20-%20Time_Series/S%C3%A9rie%20Temporal.ipynb
    github: https://github.com/felipesembay/Udacity/blob/master/Projeto4%20-%20Time_Series/S%C3%A9rie%20Temporal.ipynb
    img: https://cdn.glitch.com/e97af72f-6650-41fb-b7ca-5a4cdd42ea0c%2Fprevisao-de-vendas.jpeg?v=1591147711535
    tags: [Machine Learning, Python, Arima, ETS, Prophet]
    
  


# Certifications 
awards:
  - Data Science do Zero - Minerando Dados
  - Python para Data Science e Machine Learning - Completo - Udemy
  - Python para Finanças, Investimentos e Analise de Dados - Udemy
  - Predictive Analytics for Business - Udacity
  - Inteligência Artificial Fundamentos - Data Science Academy
  - Into to SQL for Data Science - DataCamp
  - Fundamentos de Análise de Dados - Udacity
  - Aprendendo Programar em R - Udemy
